:sparkles: (kyungdeok/featrue/searchResult/\#35) 검색결과창 구현
ILGOB/Plinic-iOS pull request #37
Opened 2022-09-06 15:12 UTC by N0Rib

확인 후 수정할 사항 있으면 연락 주시길 바랍니다

2022-09-07 07:20 UTC, blooper20 requested changes
의욕이 떨어지고 있는게 보이지만 따라와줘서 고맙고 수정해달라는 부분 수정해주고 추석연휴 동안 기력 되찾고 파이팅있게 끝까지 해봅시다.

2022-09-07 07:20 UTC, blooper20 commented on Plinic/search/searchViews/searchResult.swift
> +                            .padding(.leading, 10.0)
이 부분 전체를 하나의 파일(userResult)로 만들어주고 최상단 결과인 뷰 파일(userTopResult)을 하나 더 만든 후에 
UserResult().scaleEffect(스케일 키울 float값)
을 활용하여 만드는게 더 좋을거 같음
또한
```suggestion
                            VStack{
                               Image(profileImg)
                                .resizeable()
                                .aspectRatio(contentMode: .fill)
                                .clipShape(Circle())
                                // 이미지를 동그란형태로 클립하여 백엔드에서 이미지 정보를 주었을 때 profileImg 변수로 동작할수 있게끔 수정 바람
                                Text("\(nickName)")
                                    .foregroundColor(Color.white)
                                    .fontWeight(.bold)
                                    .font(.system(size: 15))
                                
                            }//VStack
                            .padding(.leading, 10.0)
```

2022-09-07 07:20 UTC, blooper20 commented on Plinic/search/searchViews/searchResult.swift
> +                        .padding(.top, 20.0)
이 부분과 밑에있는 '검색결과 더보기' Button을 위에 "상위검색결과" Text와 같은 라인에 있게 HStack으로 수정 바람

2022-09-07 07:20 UTC, blooper20 commented on Plinic/search/searchViews/searchResult.swift
> +                                VStack(spacing:0) {
이쪽은 postCreate 파일을 참고하여 두개의 게시글이 보이는게 아닌 3개의 게시글이 보이는게 더욱 좋아보임

2022-09-12 07:38 UTC, N0Rib commented
수정하라는 부분 완료 했습니다 확인 후 다시 수정할 부분 알려주세요

2022-09-13 13:01 UTC, blooper20 reviewed
요구사항에 맞게 잘 수정하셨습니다

2022-09-13 13:02 UTC, merged